<?php

$controllers = [
    // ----------------- DASHBOARD -----------------
    'app/Http/Controllers/Admin/DashboardController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\{User, Store, Product, Order};\n\nclass DashboardController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$data = [\n            'total_users' => User::count(),\n            'total_stores' => Store::count(),\n            'total_products' => Product::count(),\n            'total_orders' => Order::count(),\n        ];\n        if (\$request->wantsJson()) return response()->json(\$data);\n        return view('admin.dashboard', compact('data'));\n    }\n}\n",
    
    // ----------------- USER -----------------
    'app/Http/Controllers/Admin/UserController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\User;\n\nclass UserController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$users = User::all();\n        if (\$request->wantsJson()) return response()->json(\$users);\n        return view('admin.users.index', compact('users'));\n    }\n\n    public function updateStatus(Request \$request, \$id)\n    {\n        \$user = User::findOrFail(\$id);\n        \$user->update(['status_akun' => \$request->input('status_akun', 'aktif')]);\n        if (\$request->wantsJson()) return response()->json(['message' => 'Status akun diperbarui', 'user' => \$user]);\n        return redirect()->back()->with('success', 'Status akun diperbarui');\n    }\n\n    public function destroy(Request \$request, \$id)\n    {\n        \$user = User::findOrFail(\$id);\n        \$user->delete();\n        if (\$request->wantsJson()) return response()->json(['message' => 'Akun dihapus']);\n        return redirect()->back()->with('success', 'Akun dihapus');\n    }\n}\n",

    // ----------------- STORE -----------------
    'app/Http/Controllers/Admin/StoreController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Store;\n\nclass StoreController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$stores = Store::with('user')->get();\n        if (\$request->wantsJson()) return response()->json(\$stores);\n        return view('admin.stores.index', compact('stores'));\n    }\n\n    public function verify(Request \$request, \$id)\n    {\n        \$store = Store::findOrFail(\$id);\n        \$store->update(['status_verifikasi' => \$request->input('status', 'disetujui')]);\n        if (\$request->wantsJson()) return response()->json(['message' => 'Toko diverifikasi', 'store' => \$store]);\n        return redirect()->back()->with('success', 'Status toko diperbarui');\n    }\n}\n",

    // ----------------- CATEGORY -----------------
    'app/Http/Controllers/Admin/CategoryController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Category;\n\nclass CategoryController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$categories = Category::all();\n        if (\$request->wantsJson()) return response()->json(\$categories);\n        return view('admin.categories.index', compact('categories'));\n    }\n\n    public function store(Request \$request)\n    {\n        \$request->validate(['nama_kategori' => 'required|string', 'deskripsi' => 'nullable|string']);\n        \$category = Category::create(\$request->all());\n        if (\$request->wantsJson()) return response()->json(['message' => 'Kategori dibuat', 'category' => \$category]);\n        return redirect()->back()->with('success', 'Kategori ditambahkan');\n    }\n\n    public function update(Request \$request, \$id)\n    {\n        \$category = Category::findOrFail(\$id);\n        \$request->validate(['nama_kategori' => 'required|string', 'deskripsi' => 'nullable|string']);\n        \$category->update(\$request->all());\n        if (\$request->wantsJson()) return response()->json(['message' => 'Kategori diperbarui', 'category' => \$category]);\n        return redirect()->back()->with('success', 'Kategori diperbarui');\n    }\n\n    public function destroy(Request \$request, \$id)\n    {\n        Category::findOrFail(\$id)->delete();\n        if (\$request->wantsJson()) return response()->json(['message' => 'Kategori dihapus']);\n        return redirect()->back()->with('success', 'Kategori dihapus');\n    }\n}\n",

    // ----------------- PRODUCT -----------------
    'app/Http/Controllers/Admin/ProductController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Product;\n\nclass ProductController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$products = Product::with(['store', 'category'])->get();\n        if (\$request->wantsJson()) return response()->json(\$products);\n        return view('admin.products.index', compact('products'));\n    }\n\n    public function destroy(Request \$request, \$id)\n    {\n        Product::findOrFail(\$id)->delete();\n        if (\$request->wantsJson()) return response()->json(['message' => 'Produk dihapus']);\n        return redirect()->back()->with('success', 'Menu berhasil dihapus oleh sistem');\n    }\n}\n",

    // ----------------- ORDER -----------------
    'app/Http/Controllers/Admin/OrderController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Order;\n\nclass OrderController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$orders = Order::with(['user', 'store', 'kurir'])->get();\n        if (\$request->wantsJson()) return response()->json(\$orders);\n        return view('admin.orders.index', compact('orders'));\n    }\n\n    public function show(Request \$request, \$id)\n    {\n        \$order = Order::with(['orderDetails.product', 'user', 'store', 'kurir', 'payment', 'verification'])->findOrFail(\$id);\n        if (\$request->wantsJson()) return response()->json(\$order);\n        return view('admin.orders.show', compact('order'));\n    }\n}\n",

    // ----------------- REVIEW -----------------
    'app/Http/Controllers/Admin/ReviewController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Review;\n\nclass ReviewController extends Controller\n{\n    public function index(Request \$request)\n    {\n        \$reviews = Review::with(['user', 'product'])->get();\n        if (\$request->wantsJson()) return response()->json(\$reviews);\n        return view('admin.reviews.index', compact('reviews'));\n    }\n\n    public function destroy(Request \$request, \$id)\n    {\n        Review::findOrFail(\$id)->delete();\n        if (\$request->wantsJson()) return response()->json(['message' => 'Ulasan dihapus']);\n        return redirect()->back()->with('success', 'Ulasan dihapus');\n    }\n}\n",

    // ----------------- REPORT -----------------
    'app/Http/Controllers/Admin/ReportController.php' => "<?php\n\nnamespace App\Http\Controllers\Admin;\n\nuse App\Http\Controllers\Controller;\nuse Illuminate\Http\Request;\nuse App\Models\Monitoring;\n\nclass ReportController extends Controller\n{\n    public function index(Request \$request)\n    {\n        // Assuming Monitoring is used for system logs/reports. Or we create a Report model later.\n        \$reports = Monitoring::with('user')->get();\n        if (\$request->wantsJson()) return response()->json(\$reports);\n        return view('admin.reports.index', compact('reports'));\n    }\n\n    public function resolve(Request \$request, \$id)\n    {\n        // Logic to mark a report as resolved\n        if (\$request->wantsJson()) return response()->json(['message' => 'Laporan diselesaikan']);\n        return redirect()->back()->with('success', 'Laporan telah diselesaikan');\n    }\n}\n",
];

foreach ($controllers as $path => $content) {
    file_put_contents($path, $content);
    echo "Updated $path\n";
}
