<?php

$models = [
    'Store' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Store extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_toko';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function products() { return \$this->hasMany(Product::class, 'id_toko'); }\n}\n",
    'Category' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Category extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_kategori';\n    protected \$guarded = [];\n\n    public function products() { return \$this->hasMany(Product::class, 'id_kategori'); }\n}\n",
    'Product' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Product extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_produk';\n    protected \$guarded = [];\n\n    public function store() { return \$this->belongsTo(Store::class, 'id_toko'); }\n    public function category() { return \$this->belongsTo(Category::class, 'id_kategori'); }\n    public function carts() { return \$this->hasMany(Cart::class, 'id_produk'); }\n    public function orderDetails() { return \$this->hasMany(OrderDetail::class, 'id_produk'); }\n    public function reviews() { return \$this->hasMany(Review::class, 'id_produk'); }\n    public function favorites() { return \$this->hasMany(Favorite::class, 'id_produk'); }\n}\n",
    'Cart' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Cart extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_keranjang';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function product() { return \$this->belongsTo(Product::class, 'id_produk'); }\n}\n",
    'Order' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Order extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_pesanan';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function store() { return \$this->belongsTo(Store::class, 'id_toko'); }\n    public function kurir() { return \$this->belongsTo(User::class, 'id_kurir'); }\n    public function orderDetails() { return \$this->hasMany(OrderDetail::class, 'id_pesanan'); }\n    public function payment() { return \$this->hasOne(Payment::class, 'id_pesanan'); }\n    public function verification() { return \$this->hasOne(Verification::class, 'id_pesanan'); }\n}\n",
    'OrderDetail' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass OrderDetail extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_detail';\n    protected \$guarded = [];\n\n    public function order() { return \$this->belongsTo(Order::class, 'id_pesanan'); }\n    public function product() { return \$this->belongsTo(Product::class, 'id_produk'); }\n}\n",
    'Payment' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Payment extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_pembayaran';\n    protected \$guarded = [];\n\n    public function order() { return \$this->belongsTo(Order::class, 'id_pesanan'); }\n}\n",
    'Review' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Review extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_ulasan';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function product() { return \$this->belongsTo(Product::class, 'id_produk'); }\n}\n",
    'Favorite' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Favorite extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_favorit';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function product() { return \$this->belongsTo(Product::class, 'id_produk'); }\n}\n",
    'Notification' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Notification extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_notifikasi';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n}\n",
    'Verification' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Verification extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_verifikasi';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n    public function order() { return \$this->belongsTo(Order::class, 'id_pesanan'); }\n    public function payment() { return \$this->belongsTo(Payment::class, 'id_pembayaran'); }\n}\n",
    'Monitoring' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Monitoring extends Model\n{\n    use HasFactory;\n    protected \$primaryKey = 'id_log';\n    protected \$guarded = [];\n\n    public function user() { return \$this->belongsTo(User::class, 'id_user'); }\n}\n",
];

foreach ($models as $name => $content) {
    file_put_contents('app/Models/' . $name . '.php', $content);
    echo "Updated $name\n";
}
